### PR TITLE
fix: create table for recursive inscriptions count

### LINKED ISSUE #236: List Inscriptions API times out while looking for recursive=true
**Describe the bug**
The list Inscriptions API times out while looking for recursive=true. Below is the error:

**To Reproduce**
 Execute the below command:
 `curl -L 'https://api.hiro.so/ordinals/v1/inscriptions?recursive=true&limit=40' \
-H 'Accept: application/json'
`

**Expected behavior**
Expected behaviour is to return a json list of inscriptions that has recursive set to true.

**Screenshots**
Below is the error it returns
`data: {
      statusCode: 500,
      code: '57014',
      error: 'Internal Server Error',
      message: 'canceling statement due to statement timeout'
    }`

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
It does work, but not always. I'd say 10% success rate.

### PR DESCRIPTION
**Pull request by rafaelcr**
Also fix rollback count decrease for genesis address

Fixes #236

### CODE REVIEW

File: src/pg/counts/counts-pg-store.ts [hunk 1]
```diff
@@ -54,58 +56,76 @@ export class CountsPgStore extends BasePgStoreModule {
...
-        });
-        rarity.set(i.sat_rarity, {
-          sat_rarity: i.sat_rarity,
-          count: rarity.get(i.sat_rarity)?.count ?? 0 + 1,
-        });
-        type.set(t, { type: t, count: type.get(t)?.count ?? 0 + 1 });
-      }
-      await sql`
-        INSERT INTO counts_by_mime_type ${sql([...mimeType.values()])}
+    const mimeType = new Map<string, any>();
```
Comment (janniks) [inline src/pg/counts/counts-pg-store.ts:59]: Curious why we are removing the write-transaction?

Comment (rafaelcr) [reply src/pg/counts/counts-pg-store.ts:59]: It's not being removed, the diff looks a bit weird but I'm performing all the writes in a single query (using `WITH x AS ()`)

Comment (rafaelcr) [reply src/pg/counts/counts-pg-store.ts:59]: Oh I think you're asking about the `writeTransaction`, that's no longer necessary because I only run 1 query now instead of several

File: src/pg/counts/counts-pg-store.ts [hunk 2]
```diff
@@ -213,6 +233,16 @@ export class CountsPgStore extends BasePgStoreModule {
...
   }
 
+  private async getRecursiveCount(recursive?: boolean): Promise<number> {
+    const rec = recursive !== undefined ? [recursive] : [true, false];
+    const result = await this.sql<{ count: number }[]>`
+      SELECT COALESCE(SUM(count), 0) AS count
+      FROM counts_by_recursive
+      WHERE recursive IN ${this.sql(rec)}
+    `;
+    return result[0].count;
```
Comment (janniks) [inline src/pg/counts/counts-pg-store.ts:243]: Interesting combo of `IN []` and `[0].count`. I guess, it really doesn't matter performance-wise, since it's max 2 rows 😅

**Review by janniks — APPROVED** [review]
Looks good ✨

File: tests/inscriptions.test.ts [hunk 3]
```diff
@@ -2958,37 +2958,36 @@ describe('/inscriptions', () => {
...
+            ordinal_block_height: 650000,
+            ordinal_offset: 0,
+            satpoint_post_inscription:
+              '38c46a8bf7ec90bc7f6b797e7dc84baa97f4e5fd4286b92fe1b50176d03b18dc:0:0',
+            inscription_input_index: 0,
+            transfers_pre_inscription: 0,
+            tx_index: 0,
+          })
+          .build();
+        await db.updateInscriptions(genesis2);
```
Comment (janniks) [inline tests/inscriptions.test.ts:2990]: This test isn't testing recursive counts right? Should we add a test-case (would that require adding real content-bytes?)

Comment (rafaelcr) [reply tests/inscriptions.test.ts:2990]: This test is for the `counts_by_genesis_address` fix. The recursion test is covered by another test within this file named `filters by recursive`. The test already existed before so there was no need to change anything 👍

Comment (janniks) [reply tests/inscriptions.test.ts:2990]: 🙌
